export const tags = [
    {name: "Biography", slug: "biography"},
    {name: "Business", slug: "business"},
    {name: "Children", slug: "children"},
    {name: "Classics", slug: "classics"},
    {name: "Cookbooks", slug: "cookbooks"},
    {name: "Comics", slug: "comics"},
    {name: "Cookbooks", slug: "cookbooks"},
    {name: "Crime", slug: "crime"},
    {name: "Fantasy", slug: "fantasy"},
    {name: "Fiction", slug: "fiction"},
    {name: "Graphic Novels", slug: "graphic-novels"},
    {name: "Historical Fiction", slug: "historical-fiction"},
    {name: "History", slug: "history"},
    {name: "Horror", slug: "horror"},
    {name: "Humor", slug: "humor"},
    {name: "Literary Fiction", slug: "literary-fiction"},
    {name: "Memoir", slug: "memoir"},
    {name: "Mystery", slug: "mystery"},
    {name: "Non-Fiction", slug: "non-fiction"},
    {name: "Poetry", slug: "poetry"},
    {name: "Psychology", slug: "psychology"},
    {name: "Romance", slug: "romance"},
    {name: "Science", slug: "science"},
    {name: "Science Fiction", slug: "sci-fi"},
    {name: "Self-Help", slug: "self-help"},
    {name: "Short Stories", slug: "short-stories"},
    {name: "Thriller", slug: "thriller"},
    {name: "Travel", slug: "travel"},
    {name: "Young Adult", slug: "young-adult"}
]